### PR TITLE
fix: generic type on event arg in onClickAway callback on useClickAway

### LINKED ISSUE #393: useClickAway: callback event definition KeyboardEvent is not enough
The TypeScript declaration for the [callback](https://github.com/streamich/react-use/blob/v9.4.1/src/useClickAway.ts#L8) is:

```TypeScript
onClickAway: (event: KeyboardEvent) => void
```

KeyboardEvent is not enough, it should be: `KeyboardEvent | TouchEvent | MouseEvent | ...` or more probably `UIEvent` and then the user should cast it to MouseEvent, KeyboardEvent... depending on the parameters he passed to useClickAway()

### PR DESCRIPTION
**Pull request by frfroes**
Fixes #393

# Description

I'm using generic typing on the hook definition to provide the user the ability to type the `onClickAway` callback's arg in the way it better suits her/his needs. The generic is extending and falling back to the `Event` type because it was the most generic one I could think would be relevant for this scenario. 

## Type of change

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] **Breaking change** _(fix or feature that would cause existing functionality to not work as before)_

# Checklist
- [x] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [x] Perform a code self-review
- [x] Comment the code, particularly in hard-to-understand areas
- [x] Add documentation
- [x] Add hook's story at Storybook
- [x] Cover changes with tests
- [x] Ensure the test suite passes (`yarn test`)
- [x] Provide 100% tests coverage
- [x] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [x] Make sure types are fine (`yarn lint:types`).

### CODE REVIEW

File: src/useClickAway.ts [hunk 1]
```diff
@@ -3,9 +3,9 @@ import { off, on } from './util';
 
 const defaultEvents = ['mousedown', 'touchstart'];
 
-const useClickAway = (
+const useClickAway = <T extends Event>(
```
Comment (streamich) [inline src/useClickAway.ts]: Would default help here?

```suggestion
const useClickAway = <T extends Event = Event>(
```

File: src/useClickAway.ts [hunk 2]
```diff
@@ -3,9 +3,9 @@ import { off, on } from './util';
...
   ref: RefObject<HTMLElement | null>,
-  onClickAway: (event: KeyboardEvent) => void,
+  onClickAway: (event: T | Event) => void,
```
Comment (streamich) [inline src/useClickAway.ts]: Is `Event` needed here?

```suggestion
  onClickAway: (event: T) => void,
```
